// <auto-generated />
using System;
using HospitalTestTask.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalTestTask.Infrastructure.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HospitalTestTask.Application.Models.DistrictPart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("DistrictPart");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Number = 112L
                        },
                        new
                        {
                            Id = 2L,
                            Number = 113L
                        },
                        new
                        {
                            Id = 3L,
                            Number = 114L
                        },
                        new
                        {
                            Id = 4L,
                            Number = 115L
                        },
                        new
                        {
                            Id = 5L,
                            Number = 116L
                        });
                });

            modelBuilder.Entity("HospitalTestTask.Application.Models.Doctor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("DistrictPartId")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OfficeId")
                        .HasColumnType("bigint");

                    b.Property<long>("SpecializationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DistrictPartId");

                    b.HasIndex("OfficeId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DistrictPartId = 3L,
                            FullName = "Doctor_FullName_1",
                            OfficeId = 5L,
                            SpecializationId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            FullName = "Doctor_FullName_2",
                            OfficeId = 2L,
                            SpecializationId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            FullName = "Doctor_FullName_3",
                            OfficeId = 3L,
                            SpecializationId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            DistrictPartId = 1L,
                            FullName = "Doctor_FullName_4",
                            OfficeId = 1L,
                            SpecializationId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            DistrictPartId = 5L,
                            FullName = "Doctor_FullName_5",
                            OfficeId = 4L,
                            SpecializationId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            DistrictPartId = 2L,
                            FullName = "Doctor_FullName_6",
                            OfficeId = 3L,
                            SpecializationId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            FullName = "Doctor_FullName_7",
                            OfficeId = 1L,
                            SpecializationId = 3L
                        });
                });

            modelBuilder.Entity("HospitalTestTask.Application.Models.Office", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Office");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Number = 210
                        },
                        new
                        {
                            Id = 2L,
                            Number = 220
                        },
                        new
                        {
                            Id = 3L,
                            Number = 213
                        },
                        new
                        {
                            Id = 4L,
                            Number = 314
                        },
                        new
                        {
                            Id = 5L,
                            Number = 302
                        });
                });

            modelBuilder.Entity("HospitalTestTask.Application.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("DistrictPartId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictPartId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("093860d8-5413-4e15-bfad-7375fcbdc664"),
                            Address = "Address_1_1",
                            BirthDate = new DateTime(2022, 10, 15, 13, 50, 37, 902, DateTimeKind.Local).AddTicks(6954),
                            DistrictPartId = 3L,
                            Gender = 0,
                            Name = "Patient_FirstName_1",
                            Patronymic = "Patient_Patronymic_1",
                            Surname = "Patient_Surname_1"
                        },
                        new
                        {
                            Id = new Guid("cdfd7e0b-39fb-41bc-8d1c-614b0c52303e"),
                            Address = "Address_21_5",
                            BirthDate = new DateTime(2022, 10, 15, 13, 50, 37, 904, DateTimeKind.Local).AddTicks(1050),
                            DistrictPartId = 1L,
                            Gender = 1,
                            Name = "Patient_FirstName_2",
                            Patronymic = "Patient_Patronymic_2",
                            Surname = "Patient_Surname_2"
                        },
                        new
                        {
                            Id = new Guid("19ac7d06-b910-4e5d-8e6b-fa259cb2cffc"),
                            Address = "Address_12_22",
                            BirthDate = new DateTime(2022, 10, 15, 13, 50, 37, 904, DateTimeKind.Local).AddTicks(1061),
                            DistrictPartId = 3L,
                            Gender = 0,
                            Name = "Patient_FirstName_3",
                            Surname = "Patient_Surname_3"
                        },
                        new
                        {
                            Id = new Guid("c042d2cb-43d4-499d-bcc4-3d7036035dde"),
                            Address = "Address_224_4",
                            BirthDate = new DateTime(2022, 10, 15, 13, 50, 37, 904, DateTimeKind.Local).AddTicks(1063),
                            DistrictPartId = 2L,
                            Gender = 0,
                            Name = "Patient_FirstName_4",
                            Patronymic = "Patient_Patronymic_4",
                            Surname = "Patient_Surname_4"
                        },
                        new
                        {
                            Id = new Guid("aef2ac54-d4fb-43c6-b397-065f63ecbdc3"),
                            Address = "Address_5_44",
                            BirthDate = new DateTime(2022, 10, 15, 13, 50, 37, 904, DateTimeKind.Local).AddTicks(1065),
                            DistrictPartId = 3L,
                            Gender = 0,
                            Name = "Patient_FirstName_5",
                            Patronymic = "Patient_Patronymic_5",
                            Surname = "Patient_Surname_5"
                        },
                        new
                        {
                            Id = new Guid("6a268677-aaa7-4527-8a55-3db666c9464a"),
                            Address = "Address_7_4",
                            BirthDate = new DateTime(2022, 10, 15, 13, 50, 37, 904, DateTimeKind.Local).AddTicks(1067),
                            DistrictPartId = 2L,
                            Gender = 1,
                            Name = "Patient_FirstName_6",
                            Patronymic = "Patient_Patronymic_6",
                            Surname = "Patient_Surname_6"
                        },
                        new
                        {
                            Id = new Guid("833fe5f0-60eb-4fbb-9513-feb9af5e3d84"),
                            Address = "Address_1_1",
                            BirthDate = new DateTime(2022, 10, 15, 13, 50, 37, 904, DateTimeKind.Local).AddTicks(1076),
                            DistrictPartId = 1L,
                            Gender = 1,
                            Name = "Patient_FirstName_7",
                            Patronymic = "Patient_Patronymic_7",
                            Surname = "Patient_Surname_7"
                        },
                        new
                        {
                            Id = new Guid("da1e200f-eb7f-427d-b186-36e4f8219818"),
                            Address = "Address_22_41",
                            BirthDate = new DateTime(2022, 10, 15, 13, 50, 37, 904, DateTimeKind.Local).AddTicks(1077),
                            DistrictPartId = 4L,
                            Gender = 0,
                            Name = "Patient_FirstName_8",
                            Patronymic = "Patient_Patronymic_8",
                            Surname = "Patient_Surname_8"
                        });
                });

            modelBuilder.Entity("HospitalTestTask.Application.Models.Specialization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specialization");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Терапевт"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Хирург"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Офтальмолог"
                        });
                });

            modelBuilder.Entity("HospitalTestTask.Application.Models.Doctor", b =>
                {
                    b.HasOne("HospitalTestTask.Application.Models.DistrictPart", "DistrictPart")
                        .WithMany()
                        .HasForeignKey("DistrictPartId");

                    b.HasOne("HospitalTestTask.Application.Models.Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalTestTask.Application.Models.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DistrictPart");

                    b.Navigation("Office");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("HospitalTestTask.Application.Models.Patient", b =>
                {
                    b.HasOne("HospitalTestTask.Application.Models.DistrictPart", "DistrictPart")
                        .WithMany()
                        .HasForeignKey("DistrictPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DistrictPart");
                });
#pragma warning restore 612, 618
        }
    }
}
